export const PAGE_LOG_FINANCES = "PAGE_MANAGE_PERSONAL_DATA";

export const INPUT_ADD_BUDGET = "INPUT_ADD_BUDGET";
export const INPUT_ADD_EXPENSE = "INPUT_ADD_EXPENSE";
export const INPUT_UPDATE_BUDGET_NAME = "INPUT_UPDATE_BUDGET_NAME";
export const INPUT_UPDATE_BUDGET_AMOUNT = "INPUT_UPDATE_BUDGET_AMOUNT";
export const INPUT_UPDATE_EXPENSE_DESCRIPTION = "INPUT_UPDATE_EXPENSE_DESCRIPTION";
export const INPUT_UPDATE_EXPENSE_AMOUNT = "INPUT_UPDATE_EXPENSE_AMOUNT";

export const LOCAL_STORAGE_BUDGET_LIST = "LOCAL_STORAGE_BUDGET_LIST";
export const LOCAL_STORAGE_EXPENSE_LIST = "LOCAL_STORAGE_EXPENSE_LIST";

export const BUTTON_LABEL_ADD_BUDGET = "Add Budget";
export const BUTTON_UPDATE_BUDGET_AMOUNT = "Update Budget Amount";
export const BUTTON_UPDATE_BUDGET_NAME = "Update Budget Name";
export const BUTTON_LABEL_ADD_EXPENSE = "Add Expense";
export const BUTTON_LABEL_UPDATE_EXPENSE_AMOUNT = "Update Expense Amount";
export const BUTTON_LABEL_UPDATE_EXPENSE_DESCRIPTION = "Update Expense Description";