export const PAGE_LOG_FINANCES = "PAGE_LOG_FINANCES";
export const PAGE_RUNNING_TABS = "PAGE_RUNNING_TABS";
export const PAGE_PROJECTIONS = "PAGE_PROJECTIONS";

export const INPUT_ADD_BUDGET = "INPUT_ADD_BUDGET";
export const INPUT_ADD_EXPENSE = "INPUT_ADD_EXPENSE";
export const INPUT_UPDATE_BUDGET_NAME = "INPUT_UPDATE_BUDGET_NAME";
export const INPUT_UPDATE_BUDGET_AMOUNT = "INPUT_UPDATE_BUDGET_AMOUNT";
export const INPUT_UPDATE_EXPENSE_DESCRIPTION = "INPUT_UPDATE_EXPENSE_DESCRIPTION";
export const INPUT_UPDATE_EXPENSE_AMOUNT = "INPUT_UPDATE_EXPENSE_AMOUNT";
export const INPUT_ADD_TAB = "INPUT_ADD_TAB";
export const INPUT_UPDATE_TAB_NAME = "INPUT_UPDATE_TAB_NAME";
export const INPUT_ADD_TAB_PERSON = "INPUT_ADD_TAB_PERSON";
export const INPUT_UPDATE_TAB_PERSON_NAME = "INPUT_UPDATE_TAB_PERSON_NAME";
export const INPUT_ADD_TAB_RECORD = "INPUT_ADD_TAB_RECORD";

export const LOCAL_STORAGE_BUDGET_LIST = "LOCAL_STORAGE_BUDGET_LIST";
export const LOCAL_STORAGE_EXPENSE_LIST = "LOCAL_STORAGE_EXPENSE_LIST";
export const LOCAL_STORAGE_TABS_LIST = "LOCAL_STORAGE_TABS_LIST";
export const LOCAL_STORAGE_INCOMES_LIST = "LOCAL_STORAGE_INCOMES_LIST"

export const BUTTON_LABEL_ADD_BUDGET = "Add Budget";
export const BUTTON_UPDATE_BUDGET_AMOUNT = "Update Budget Amount";
export const BUTTON_UPDATE_BUDGET_NAME = "Update Budget Name";
export const BUTTON_LABEL_ADD_EXPENSE = "Add Expense";
export const BUTTON_LABEL_UPDATE_EXPENSE_AMOUNT = "Update Amount Spent";
export const BUTTON_LABEL_UPDATE_EXPENSE_DESCRIPTION = "Update Description";
export const BUTTON_LABEL_ADD_TAB = "Add Tab";
export const BUTTON_LABEL_ADD_TAB_PERSON = "Add Person"
export const BUTTON_UPDATE_TAB_NAME = "Update Name"
export const BUTTON_ADD_TAB_RECORD = "Add Record"